name: 'Bump version using labels'
description: 'Provide a description here'
author: 'Xavier Chretien'
inputs:
  patch_label:
    description: Label used to update the minor version (x.x.PATCH)
    default: 'version: Patch'
    required: false
  minor_label:
    description: Label used to update the minor version (x.MINOR.x)
    default: 'version: Minor'
    required: false
  major_label:
    description: Label used to update the minor version (MAJOR.x.x)
    default: 'version: Major'
    required: false
  look_for_tag:
    description: Tag in the file that contains the version.
    default: 'version'
    required: false
  file_path:
    description: Path to the file that contains the version. The file should be a YAML or a JSON file
    required: true
  use_tag_as_ref:
    description: Use the tags of the repository to determine the latest version.
    default: 'false'
    required: true
  reference_branch:
    description: Use the specified branch to determine the latest version used. Ignored if `use_tag_as_ref` is true.
    default: 'main'
    required: false

  comment:
    description: Comment the pull request when the version is update or when there is an error. Set to `false` to disable.
    default: 'true'
    required: false
  comment_message:
    description: Message used for the comment. You can use '{old}' and '{new}' to display the ancient and new version. Ignored if `comment` is false.
    default: 'Bump version from {old} to {new}'
    required: false

  commit:
    description: Commit the changed file. Set to `false` to disable.
    default: 'true'
    required: false
  commit_message:
    description: Message used for the commit. You can use '{old}' and '{new}' to display the ancient and new version. Ignored if `commit` is false.
    default: '[BOT] Bump version from {old} to {new}'
    required: false
  commit_options:
    description: Commit options (eg. --no-verify). Ignored if `commit` is false.
    default: ''
    required: false
  commit_branch:
    description: Git branch name, where changes should be pushed too. Ignored if `commit` is false.
    default: ${{ github.head_ref }}
    required: false
  commit_user_name:
    description: Name used for the commit user. Ignored if `commit` is false.
    default: 'GitHub Actions'
    required: false
  commit_user_email:
    description: Email address used for the commit user. Ignored if `commit` is false.
    default: 'actions@github.com'
    required: false
  repository:
    description: Local file path to the git repository. Defaults to the current directory (`.`). Ignored if `commit` is false.
    default: '.'
    required: false

outputs:
  version:
    description: Current version.

runs:
  using: 'node16'
  main: 'dist/index.js'
