name: 'test'
on: # rebuild any PRs and main branch changes
  pull_request:
    types:
      - unlabeled
      - labeled
      - synchronize
      - opened
      - reopened
jobs:
  test: # make sure the action works on a clean machine
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm install
      - run: |
          npm run build
      - uses: ./
        with:
          file_path: 'package.json'
          minor_label: 'Increase: minor version'
          comment: true
